TRAIN_DS = "fundus_ds/Training_Set/Training_Set/Training/"
TRAIN_CSV = "fundus_ds/Training_Set/Training_Set/RFMiD_Training_Labels.csv"
VAL_DS = "fundus_ds/Evaluation_Set/Evaluation_Set/Validation/"
VAL_CSV = "fundus_ds/Evaluation_Set/Evaluation_Set/RFMiD_Validation_Labels.csv"
TEST_DS = "fundus_ds/Test_Set/Test_Set/Test/"
TEST_CSV = "fundus_ds/Test_Set/Test_Set/RFMiD_Testing_Labels.csv"